services:

  hbase:

    build:
      context: ..
      dockerfile: docker/Dockerfiles/Dockerfile.hbase

    image: hbase-custom:2.6.5

    container_name: hbase

    hostname: hbase

    restart: unless-stopped

    ports:
      - "16000:16000"
      - "16010:16010"
      - "16020:16020"
      - "16030:16030"

    volumes:

      # Project files (Python, shell scripts, schemas)
      - ../../hbase:/workspace/hbase

      # HBase configs
      - ../hbase/hbase-site.xml:/opt/hbase/conf/hbase-site.xml:ro
      - ../hbase/regionservers:/opt/hbase/conf/regionservers:ro
      - ../hbase/start-hbase.sh:/start-hbase.sh:ro

      # Hadoop configs
      - ../hadoop/core-site.xml:/etc/hadoop/core-site.xml:ro
      - ../hadoop/hdfs-site.xml:/etc/hadoop/hdfs-site.xml:ro
      - ../hadoop/mapred-site.xml:/etc/hadoop/mapred-site.xml:ro
      - ../hadoop/yarn-site.xml:/etc/hadoop/yarn-site.xml:ro

      # Persist HBase data
      - hbase-data:/opt/hbase/data

    networks:
      - hadoop-network

networks:

  hadoop-network:
    external: true
    name: hadoop-network

volumes:

  hbase-data: