agent.sources = source1
agent.channels = channel1
agent.sinks = sink1


# ==================================================
# SOURCE
# ==================================================

agent.sources.source1.type = exec
agent.sources.source1.command = tail -F /logs/application_logs.log


# ==================================================
# CHANNEL
# ==================================================

agent.channels.channel1.type = memory
agent.channels.channel1.capacity = 10000
agent.channels.channel1.transactionCapacity = 1000


# ==================================================
# SINK
# ==================================================

agent.sinks.sink1.type = hdfs

agent.sinks.sink1.hdfs.path = hdfs://namenode:9000/bronze/logs/flume

agent.sinks.sink1.hdfs.filePrefix = application

agent.sinks.sink1.hdfs.fileType = DataStream

agent.sinks.sink1.hdfs.writeFormat = Text

agent.sinks.sink1.hdfs.rollInterval = 30
agent.sinks.sink1.hdfs.rollSize = 0
agent.sinks.sink1.hdfs.rollCount = 0

agent.sinks.sink1.hdfs.batchSize = 100

agent.sinks.sink1.hdfs.callTimeout = 60000

agent.sinks.sink1.hdfs.useLocalTimeStamp = true


# ==================================================
# BIND SOURCE -> CHANNEL -> SINK
# ==================================================

agent.sources.source1.channels = channel1

agent.sinks.sink1.channel = channel1